### Register SSO user
@baseUrl = http://localhost:12201/api/v1/
POST {{baseUrl}}auth/register
Content-Type: application/json

{
  "email": "aries@erayadigital.co.id",
  "phone": "08123456789",
  "username": "testuser",
  "password": "rahasia123",
  "role": 1,
  "registration_number": "REG-12345"
}

### Login SSO user
POST {{baseUrl}}auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "rahasia123",
  "fingerprint": "REG-12345",
  "login_from": "web"
}
